In [1]:
!git clone https://github.com/saiteja-025/flyrank-ml-internship.git

Cloning into 'flyrank-ml-internship'...
remote: Enumerating objects: 124, done.
remote: Counting objects: 100% (124/124), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 124 (delta 38), reused 92 (delta 27), pack-reused 0 (from 0)
Receiving objects: 100% (124/124), 1.85 MiB | 14.32 MiB/s, done.
Resolving deltas: 100% (38/38), done.

In [2]:
%cd flyrank-ml-internship

/content/flyrank-ml-internship

In [3]:
import os

os.listdir("data/raw")

['content_refresh_anonymized.csv']

In [4]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/saiteja-025/flyrank-ml-internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

## My Lane as an ML Task

**Task Type:** Scoring

This project is a scoring machine learning task. The goal is to estimate the quality or performance potential of a content article using features such as search volume, competition, CPC, content type, search intent, word count, and CTR. The predicted score helps decide which content should be refreshed or prioritized.

In [5]:
task_type = "Scoring"

print("ML Task Type:", task_type)

ML Task Type: Scoring

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

## Target or Proxy

The target (proxy) is the Click-Through Rate (CTR) of the content. CTR is an observed performance metric that indicates how often users click on the content after seeing it. The model will use features such as search volume, competition, CPC, content type, search intent, and word count to estimate CTR.

In [6]:
target = "ctr"

print("Target Column:", target)

if target in df.columns:
    print("\nSample Target Values:")
    print(df[target].head())
else:
    print("Target column not found.")

Target Column: ctr

Sample Target Values:
0    0.76
1    0.05
2    0.09
3    0.49
4    0.13
Name: ctr, dtype: float64

## 3. Success metric

*One metric you can defend. What number means 'good'?*

## Success Metric

The success metric for this task is **Mean Absolute Error (MAE)**. MAE measures the average difference between the predicted CTR and the actual CTR values. A lower MAE indicates that the model predicts content performance more accurately, making it useful for prioritizing content refresh decisions.

In [7]:
success_metric = "Mean Absolute Error (MAE)"

print("Success Metric:", success_metric)
print("Goal: Lower MAE means better prediction accuracy.")

Success Metric: Mean Absolute Error (MAE)
Goal: Lower MAE means better prediction accuracy.

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

## The Unit of Analysis

The unit of analysis is **one content article**. Each row in the dataset represents a single content item with SEO and content-related features such as search volume, competition, CPC, content type, search intent, word count, and CTR. These features are used to analyze and predict the content's performance.

In [8]:
# Display the first five rows of the dataset
print("First 5 rows of the dataset:")
display(df.head())

print("\nShape of the dataset:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nUnit of Analysis:")
print("Each row represents one content article.")

First 5 rows of the dataset:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

Shape of the dataset: (30000, 44)

Columns:
['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

Unit of Analysis:
Each row represents one content article.

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

## Why ML Beats a Fixed Rule

A fixed rule cannot accurately predict content performance because many factors influence the outcome, such as search volume, competition, CPC, content type, search intent, and content length. The relationship between these features is complex and changes over time. A machine learning model can learn these patterns from historical data and provide better predictions than manually written rules. This helps in making better decisions about which content should be refreshed or prioritized.

In [9]:
reason = (
    "Machine Learning is preferred because content performance depends on "
    "multiple interacting features rather than a single fixed rule."
)

print(reason)

Machine Learning is preferred because content performance depends on multiple interacting features rather than a single fixed rule.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.